package org.usfirst.frc2667.PowerUp.subsystems;

import org.usfirst.frc2667.PowerUp.RobotMap;
import org.usfirst.frc2667.PowerUp.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.DigitalInput;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class CubeGrab extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX grabWindow = RobotMap.cubeGrabGrabWindow;
    private final WPI_TalonSRX liftWindow = RobotMap.cubeGrabLiftWindow;
    private final DigitalInput upperLimitSwitch = RobotMap.cubeGrabUpperLimitSwitch;
    private final DigitalInput lowerLimitSwitch = RobotMap.cubeGrabLowerLimitSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public void stop() {
    	grabWindow.stopMotor();
    	liftWindow.stopMotor();
    }
    
    public void stopGrab() {
    	grabWindow.stopMotor();
    }
  
    public void stopLift() {
    	liftWindow.stopMotor();
    }
    
    public void grab() {
    	grabWindow.set(1);
    }
    
    public void release() {
    	grabWindow.set(-1);
    }
    
    public void lift() {
    	liftWindow.set(1);
    }
    
    public void drop() {
    	liftWindow.set(-1);
    }
    
    public boolean getLowerSwitch() {
    	return lowerLimitSwitch.get();
    }
    
    public boolean getUpperSwitch() {
    	return upperLimitSwitch.get();
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}
