// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2667.PowerUp.subsystems;

import org.usfirst.frc2667.PowerUp.RobotMap;
import org.usfirst.frc2667.PowerUp.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class SideLiftLeft extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController sideLiftLeft = RobotMap.sideLiftSideLiftLeft;
    private final Servo sideDropLeft = RobotMap.sideLiftSideDropLeft;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public void stop() {
    	sideLiftLeft.stopMotor();
    	sideDropLeft.setDisabled();
    }
    
    //TEST THIS BEFORE USING
    //WHAT POSITION WILL THE SERVO BE IN AT THE START I NEED TO KNOW
    public void drop() {
    	sideDropLeft.setPosition(.5);
    }
    
    public void drop(double pos) {
    	sideDropLeft.setPosition(0);
    }
    
    public double getDropServo() {
    	return sideDropLeft.getAngle();
    }
    
    //Is this too slow?
    public void lift() {
    	sideLiftLeft.set(1);
    }
    
    public void lift(double speed) {
    	sideLiftLeft.set(speed);
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

